---
title: "Assignment 12 - Recommender Systems: Steam gaming service "
author: "Thomas Hill"
date: "4/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Assignment Details

Your task is to analyze an existing recommender system that you find interesting.  You should:

1. Perform a Scenario Design analysis as described below.  Consider whether it makes sense for your selected recommender system to perform scenario design twice, once for the organization (e.g. Amazon.com) and once for the organization's customers.

2. Attempt to reverse engineer what you can about the site, from the site interface and any available information that you can find on the Internet or elsewhere.

3. Include specific recommendations about how to improve the site's recommendation capabilities going forward. 

4. Create your report using an R Markdown file, and create a discussion thread with a link to the GitHub repo where your Markdown file notebook resides.  You are not expected to need to write code for this discussion assignment.

Your task is to:

Identify a recommender system web site, then
Answer the three scenario design questions for this web site.  

This process of guessing/reverse engineering, while inexact, will help you build out your own ability to better account for “user needs” in designing recommender systems going forward.  Being able to place the customer first in your mind is a “soft skill” that is highly valued in the technical marketplace.


# Steam gaming service - a product by Valve

Steam is an online market for video games - primarily for PC - originally created by the game developers at Valve Studios. Steam is synonymous with digital access to third-party games, and exhibits many of the contemporary features of the gaming economy - in-game purchases occasionally referred to as 'microtransactions', digital rights management (DRM) software that authenticates access to the copyrighted material within video games, and a free API for game developers that lend independent game developers additional tools and insight into the Steam gamer community.

While the parent company Valve originally generated revenue through development and marketing of their own titles, in the last two decades it has transitioned from game development to revenue sharing of sales on Steam. From there, Steam has taken advantage of the popularity of its platform by collecting revenue from economies within the games themselves - for cosmetic or additional content, and collecting a transaction fee on trades in the Community Market. Finally, Steam enjoys the benefits of offering its own 'cash surrogate' via the Steam Wallet - a non-transferrable cash balance that can be used for purchases on Steam only.

It's evident that Steam generates a lot of revenue for envisioning a third-party platform for games, but it's also unsurprising that this business model has its detractors. Among them, enabling of gambling addiction via 'loot box' mechanics, marketing to consumers under the age of 18, and the tenuous ownership granted under some DRM lacking any physical product. Steam is also not without competitors, Activision Blizzard's _Battle.net_ and Epic Games' _Epic Games Store_ are two other examples of this sort of digital gaming platform.

## The Steam Recommender

For this assignment, I'll be looking at Steam's recommender tools, and the stakeholders they serve. Steam's array of recommender tools are available through Steam Labs, and offer several ways to browse products offered on Steam.  Browsing some operability of these tools offers some insight into how recommendations are based. The community recommendations section suggest that user-generated reviews form the basis of some of the recommendations. Steam tracks percent of positive and negative reviews generated by Steam users, in addition to monitoring their library of games and hourly play time. Players also have the option of setting up a wishlist to keep track of sales on unowned games. These community recommendations appear to be based on some type of collaborative filtering developed by Valve.

In addition, Steam gives each user the ability to search by key tags based on the genre of video game. Many of these categories are familiar - first-person shooter, puzzle, role-playing games. Other tags include 'cute', 'great soundtrack', and 'choices matter' - these appear to be less driven by an established genre and more of a distillation of reviewer insights. 

Finally, the recommender has an interactive tool touted as 'from our machine learning system' that allows users to search yet again by keywords and existing titles, and also to weigh by two additional parametrs: popularity and age.  This indicates that Valve may employ some filtering by frequency for more obscure titles and sense which games in a genre are contemporary to one seminal title - even beyond direct sequels. This last insight is also supported by use of keywords based off older game titles -- 'Metroidvania', 'Roguelike', and 'Sokoban' genres all reference much older titles and suggest an underlying genealogy of titles.

## Underlying recommender algorithms

Based on interviews with media, Valve has disclosed that it has evolved from a collaborative filtering recommender to more sophisticated neural network models. Variables considered include overall hours spent playing the game as well as patterns of use. Beyond that, Valve remains vague and only mentions that recommendations are based on 'what players do', which raises questions about how much in-game user behavior can be inferred by the external Steam client.

## Improving recommender systems

Two suggestions come to mind to improve recommendations. My strongest recommendation is likely already considered by Steam, although to which extent is not clear. A distinction between PC gaming and other types of platforms is that the hardware is not homogenous or optimized for an individual title. Offering developers insight into what hardware users have access to is important for keeping users engaged. Younger users may not have money to upgrade a computer, and playing a game on suboptimal settings can offer a poor impression of a game title. Steam already collects surveys of user hardware and software, and this information could be used to recommend older and less computationally demanding games to users on cheaper PC's. From a game developer point of view, offering 'minimal settings' modes and ensuring compatibility with as many machines as possible is pivotal to ensuring a positive user experience.

Related to this is also internet connection, which is important for games with an online multiplayer element. All games have peak user time, which may put further strain on a weak internet connection when all players are online at the same time. A recommender could track latency in a user's connection and suggest an offline or turn-based game that no longer would demand a stable internet connection. Developers could also be involved by offering titles or game modes with cross-title incentives, e.g., earn a currency in offline game 'A' that can be cashed out in online game 'B' once server conditions improve.

# Scenario design: Steam, the user, and the developers

Steam as a platform allows us to consider design for several stakeholders, the perspective of the consumer as well as the game developer. Steam has the incentive to not only promote sales by effective recommendations, but also by curating its catalog and offering some insight of user behavior to game developers.

## Users

__1. Who are the target users?__  

Users of Steam are looking for ready access to their favorite games, all in one place. Many users come with hardware limitations but unlike other game sales, there is no drive for users to make an initial investment into a game console. Therefore, the target users may start playing games casually, cooperatively with friends or between homework and social responsibilities. 

From there, patterns of game use may increase that gaming becomes a pursuit in itself. The game library becomes just that - a collection of games spanning through time and the breadth of the user's attention span.

__2. What are their goals?__  

The goal of the user is to have fun and build a healthy outlet or hobby. As mentioned earlier, many games have a cooperative or competitive element that initializes in the real world but can sustain itself in the virtual. Beyond this, many of the perks of Steam lie in convenience - one-stop, easy access to a games library. Once an initial game is bought and completed to some extent, games have options for additional challenges and customization - more fun without having to pay for yet another game.

__3. How can you help them accomplish those goals?__  

Steam already offers a robust recommender, complete with reviews pulled from internal and external sources, its own web browser and social media functionality. Recommendations should discern between the commitment users are willing to make - if not buying a whole new game, offer smaller deals within an existing game or perhaps an older, less expensive title similar to the one currently being played. Make recommendations that best fit the user's existing favorites based on similar players.

## Game Developers

__1. Who are the target users?__  

Game developers who benefit most from Steam are smaller developers without access to money for an initial investment. Beyond the actual game development, marketing for their unknown title is also expensive. Steam provides the benefits of exposure to a large user base, tools for market research and customer engagement, and particularly for new developers, rapid community feedback.

__2. What are their goals?__  

Developers are trying to sell games and keep their business profitable. Games require much of their labor done upfront, before the game is played by the end user. In lieu of an initial lump sum investment, game developers need to generate buzz about their title and get existing Steam users interested in their new title. Games can be crowdsourced, or users can be granted early access to unfinished versions of the game.

__3. How can you help them accomplish those goals?__  

Steam likely offers some limited insight into existing user profiles and usage, the most profitable genres by sales, as well as a recommender system that would place a new title one click away from an existing competitor. Steam also has early access programes and a WOrkshop that allows for rapid community input and development. 




__Sources:__  
Official site: https://store.steampowered.com/labs/  
Article on revenue: https://www.theverge.com/2018/11/30/18120577/valve-steam-game-marketplace-revenue-split-new-rules-competition/  
Article on underying ML: https://arstechnica.com/gaming/2019/07/steam-turns-to-ai-to-help-users-find-gems-amid-thousands-of-games/